version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env.keycloak

  elasticsearch:
    build:
      context: .
      dockerfile: ./elasticsearch/Dockerfile
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data

  redis:
    image: redis
    hostname: redis

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    env_file:
      - .env.keycloak
    depends_on:
    - db
    ports:
      - "8080:8080"
#    This can speed up development when working on themes in keycloak, by not requiring to rebuild the keycloak image
#    to pickup changes, instead simply restarting the keycloak container
#    volumes:
#      - ${PWD-.}/keycloak/govuk-theme/govuk:/opt/jboss/keycloak/themes/govuk

  cosmetics-web:
    build:
      context: .
      dockerfile: ./cosmetics-web/Dockerfile
    volumes:
      # ${PWD-.} calls PWD on systems which have that variable, and . on others e.g. windows
      - ${PWD-.}/cosmetics-web:/cosmetics-web
      - ${PWD-.}/shared-web:/cosmetics-web/vendor/shared-web
      - bundle-cache:/usr/local/bundle
    depends_on:
      - db
      - elasticsearch
      - keycloak
      - redis
      - cosmetics-worker
    env_file:
        - .env.keycloak.cosmetics
  cosmetics-worker:
    build:
      context: .
      dockerfile: ./cosmetics-worker/Dockerfile
    command: bin/sidekiq -C config/sidekiq.yml
    volumes:
      # ${PWD-.} calls PWD on systems which have that variable, and . on others e.g. windows
      - ${PWD-.}/cosmetics-web:/cosmetics-web
      - ${PWD-.}/shared-web:/cosmetics-web/vendor/shared-web
      - bundle-cache:/usr/local/bundle
    depends_on:
    - db
    - elasticsearch
    - redis

  mspsds-web:
    build:
      context: .
      dockerfile: ./mspsds-web/Dockerfile
    volumes:
      # ${PWD-.} calls PWD on systems which have that variable, and . on others e.g. windows
      - ${PWD-.}/mspsds-web:/mspsds-web
      - ${PWD-.}/shared-web:/mspsds-web/vendor/shared-web
      - bundle-cache:/usr/local/bundle
    depends_on:
      - db
      - elasticsearch
      - keycloak
      - redis
      - mspsds-worker
    env_file:
      - .env.keycloak.mspsds
  mspsds-worker:
    build:
      context: .
      dockerfile: ./mspsds-worker/Dockerfile
    command: bin/sidekiq -C config/sidekiq.yml
    volumes:
      # ${PWD-.} calls PWD on systems which have that variable, and . on others e.g. windows
      - ${PWD-.}/mspsds-web:/mspsds-web
      - ${PWD-.}/shared-web:/mspsds-web/vendor/shared-web
      - bundle-cache:/usr/local/bundle
    depends_on:
      - db
      - elasticsearch
      - redis

volumes:
  postgres-volume:
  elasticsearch-volume:
  bundle-cache:
